### ISSUE TITLE
httpuv v1.5.0 release checklist

### ISSUE THREAD

**Issue by jcheng5** [rstudio/httpuv#202]
- [x] If not a new package, make sure any warnings/errors in CRAN check results page are fixed
- [x] Create RC branch `rc-v1.5.0`
- [x] Change the DESCRIPTION and NEWS on this branch to change the version number to the desired version for CRAN
- [x] Perform Shiny final test pass on `rc-v1.5.0`
- [x] Clean your package directory to remove any extraneous files, including ones that are git-ignored. (Warning, this will delete any unsaved buffers in RStudio! Also, be sure to close RStudio before taking this step!) `git clean -xdf .`
- [x] Build your package. I (jcheng) personally do it from the Mac command line like this:
`PATH=$PATH:/Applications/RStudio.app/Contents/MacOS/pandoc R CMD build [pkgdir]`
- [x] Do a sanity check by installing/testing the built package.
- [x] Perform revdep check using https://github.com/r-lib/revdepcheck, if this is not the initial CRAN release.
- [x] Run `R CMD check --as-cran pkg_version.tar.gz` both locally and on win-builder. You can also use https://r-hub.github.io/rhub/.
- [x] Review CRAN Policies document
- [x] Submit to CRAN via their online form.
- [x] When accepted, tag the RC branch with a v1.5.0 tag (or whatever version you finally ended up getting accepted), and push the tag to origin.
- [x] Merge RC into master.
- [x] On master, change the package version to 1.5.0.9000.
